In [18]:
number_ones = []
for x in range(0,15):
    number_ones.append(1)
print("List of ones:")
print(number_ones)

List of ones:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [19]:
number_sevens = []
for x in range(0,15):
    number_sevens.append(7)
print("List of 7's")
print(number_sevens)

List of 7's
[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [20]:
numbers = []
for x in range(100, 151):
    numbers.append(x)
print("Numbers from 100 to 150")
print(numbers)


Numbers from 100 to 150
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [12]:
numbers_even = []
for x in range(0, 101):
    if x % 2 == 0:
        numbers_even.append(x)
print(f"List of even numbers between 0 and 100:\n {numbers_even}")




List of even numbers between 0 and 100:
 [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [21]:
years = []
for x in range(1950, 2021):
    if x % 4 == 0:
        years.append(x)
print(f"Years divisible by 4: {years}")

Years divisible by 4: [1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


2. With Numpy

In [29]:
import numpy as np

In [31]:
 %%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [33]:
array_zeros = np.zeros(15)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
array_ones = np.ones(15)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
array_sevens = np.repeat(a=7, repeats=15)
array_sevens

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [37]:
array_numbers = np.arange(100, 151)
array_numbers

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [38]:
array_numbers2 = np.arange(1900, 2022)
array_numbers2

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [56]:
array_even_numbers = np.arange(0, 101, 2)
array_even_numbers

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [66]:
array_years = np.arange(1950, 2021)
condition = array_years % 4 == 0
leap_years = array_years[condition]
leap_years


array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

Comparing Numpy codes to python's, I observe that numpy requires less codes for thesame task and pretty much straight forward.

3. Vectors and matrices

In [65]:
list = [5, 16, 9, 2, 19, 18, 11, 7]

data = np.array(list)
highest_index = data.argmax()
highest_index

4

In [67]:
data = np.arange(1, 50).reshape(7, 7)
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [87]:
matrix = []
for x in range(7):
    row = []
    for i in range(7):
        row.append(x)
    matrix.append(row)
matrix

[[0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1],
 [2, 2, 2, 2, 2, 2, 2],
 [3, 3, 3, 3, 3, 3, 3],
 [4, 4, 4, 4, 4, 4, 4],
 [5, 5, 5, 5, 5, 5, 5],
 [6, 6, 6, 6, 6, 6, 6]]

In [88]:
data_random = np.random.randint(6, size=(8, 8))
data_random

array([[4, 2, 3, 3, 1, 5, 1, 0],
       [2, 2, 4, 5, 3, 5, 5, 2],
       [0, 2, 3, 0, 3, 4, 3, 1],
       [3, 5, 3, 3, 3, 3, 2, 0],
       [3, 1, 2, 1, 0, 2, 0, 2],
       [0, 3, 3, 5, 2, 3, 4, 4],
       [3, 1, 2, 4, 2, 4, 5, 3],
       [2, 0, 1, 4, 2, 5, 4, 3]])

In [89]:
data_random_sdv = np.random.randint(-3, 4, size=(8, 8))
data_random_sdv

array([[ 2,  1,  0,  2,  1, -1,  3,  1],
       [ 1,  3,  0,  1,  3, -1,  1,  2],
       [ 3,  1,  1,  2, -3,  3, -3,  3],
       [-1,  0,  0,  3, -1, -1,  2,  1],
       [ 1,  2, -1,  2,  1,  1,  2,  1],
       [ 2,  0,  2,  3, -1,  2, -3,  1],
       [ 3, -3,  3, -3,  3,  0, -3, -3],
       [ 3, -2,  1, -2, -3,  1,  1,  1]])

In [94]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [124]:
data = np.linspace(0, 5, 100)
data_matrix = data.reshape((10,10))
data_matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

In [109]:
columns = 10
rows = 10
result_matrix = []
start = 0
end = 5
value = start
step = (end - start) / (rows * columns -1)
dataList = range(0,6)
for x in range(rows):
    listrow = []
    for i in range(columns):
        listrow.append(value)
        value += step
    result_matrix.append(listrow)
result_matrix

[[0,
  0.050505050505050504,
  0.10101010101010101,
  0.15151515151515152,
  0.20202020202020202,
  0.25252525252525254,
  0.30303030303030304,
  0.35353535353535354,
  0.40404040404040403,
  0.45454545454545453],
 [0.5050505050505051,
  0.5555555555555556,
  0.6060606060606061,
  0.6565656565656566,
  0.7070707070707071,
  0.7575757575757576,
  0.8080808080808081,
  0.8585858585858586,
  0.9090909090909091,
  0.9595959595959596],
 [1.0101010101010102,
  1.0606060606060608,
  1.1111111111111114,
  1.161616161616162,
  1.2121212121212126,
  1.2626262626262632,
  1.3131313131313138,
  1.3636363636363644,
  1.414141414141415,
  1.4646464646464656],
 [1.5151515151515162,
  1.5656565656565669,
  1.6161616161616175,
  1.666666666666668,
  1.7171717171717187,
  1.7676767676767693,
  1.81818181818182,
  1.8686868686868705,
  1.9191919191919211,
  1.9696969696969717],
 [2.020202020202022,
  2.0707070707070727,
  2.1212121212121233,
  2.171717171717174,
  2.2222222222222245,
  2.272727272727275,

In [114]:
%load_ext numpy_html

In [115]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

5. recreate matrices based on pictures

In [116]:
set1 = [23, 34, 54, 31, 75]
set2 = [33, 56, 78, 65, 97]
set3 = [41, 32, 11, 39, 51]
sets = [set1, set2, set3]

data_sets = np.array(sets)
data_sets

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [117]:
data_array = np.arange(128, 256).reshape(8, 16)
data_array

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [123]:
data = np.linspace(0.05, 5, 100)
data = np.round(data, 2)
data_10by10 = data.reshape((10,10))
data_10by10

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

# 6

In [126]:
dataset = np.arange(1, 37).reshape(6,6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [135]:
dataset = np.arange(1, 37).reshape(6,6)
subset = dataset[3:, 2:]
subset


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [140]:
dataset = np.arange(1, 37).reshape(6,6)
subset_1 = dataset[:4, 3]
subset_1

array([ 4, 10, 16, 22])

In [141]:
dataset = np.arange(1, 37).reshape(6,6)
subset_2 = dataset[2, ::]
subset_2

array([13, 14, 15, 16, 17, 18])

In [143]:
dataset = np.arange(1, 37).reshape(6,6)
subset_3 = dataset[3:, ::]
subset_3

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

# 7

In [146]:
dataset = np.arange(1, 50).reshape(7,7)
plus50 = dataset + 50
plus50

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [149]:
dataset = np.arange(1, 50).reshape(7,7)
data_sumAll = np.sum(dataset)
data_sumAll

1225

In [160]:
dataset = np.arange(1, 50).reshape(7,7)
odds = dataset[dataset % 2 != 0]
data_sum_odd = np.sum(odds)
data_sum_odd

625

In [161]:
dataset = np.arange(1, 50).reshape(7,7)
st_deviation = np.std(dataset)
st_deviation

14.142135623730951

In [164]:
dataset = np.arange(1, 50).reshape(7,7)
sum_rows = np.sum(dataset, axis=1)
sum_rows

array([ 28,  77, 126, 175, 224, 273, 322])

In [167]:
dataset = np.arange(1, 50).reshape(7,7)
sum_columns = np.sum(dataset, axis=0)
sum_columns

array([154, 161, 168, 175, 182, 189, 196])

# 7 Extra task

In [170]:
columns = 7
rows = 7
result_matrix = []
start = 1
end = 49
value = start
step = (end - start) / (rows * columns -1)
dataList = range(1,50)
for x in range(rows):
    listrow = []
    for i in range(columns):
        listrow.append(value)
        value += step
    result_matrix.append(listrow)
result_matrix

row_sums = []
for row in result_matrix:
    row_sum = sum(row)
    row_sums.append(row_sum)
row_sums

number_rows = len(result_matrix)
number_column = len(result_matrix[0])
column_sum = [0] * number_column

for row in result_matrix:
    for i in range(number_column):
        column_sum[i] += row[i]
column_sum

[154.0, 161.0, 168.0, 175.0, 182.0, 189.0, 196.0]

# 2.

In [10]:
import numpy as np
import numpy.ma as ma

dataset = np.arange(0, 50).reshape(5,10)
dataset[0] = -100
dataset_ma = ma.masked_array(dataset, mask=[0])
dataset_ma

data_unmasked = 0 == (dataset_ma < 0)
data_unmasked

masked_array(
  data=[[False, False, False, False, False, False, False, False, False,
         False],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]],
  mask=False,
  fill_value=True)

# 3.

In [12]:
manufacture_years = np.random.randint(low=2010, high=2020, size=10)
selling_price = np.random.randint(low=20000, high=60000, size=10)

print(manufacture_years)
print(selling_price)

sorter = np.argsort(manufacture_years)
print(manufacture_years[sorter])
print(selling_price[sorter])

[2013 2017 2011 2015 2011 2018 2016 2011 2015 2014]
[30770 48521 37209 46113 23105 51926 30366 27774 44739 21710]
[2011 2011 2011 2013 2014 2015 2015 2016 2017 2018]
[37209 23105 27774 30770 21710 46113 44739 30366 48521 51926]


# 4.
Additional Numpy features and possible areas of application:
a) np.repeat(): This method is used in python to repeat an element(s) multiple times in the Numpy array and also to return the repeated items of the numpy array with axix such as 0 (for columns) and 1 (for rows).

b) np.ravel(): It is used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array. The returned array has the same data type as the source array or input array but for that it is 'flatterned' (horizontal).

c) np.hsplit: It is used to split an array into multiple sub-arrays horzontally

d) np.vsplit: It is used to split an array into multiple sub-arrays vertically

e) np.hstack() and np.vstack(): These functions are used to stack arrays in sequence horizontally (column wise) and vertically respectively.

f) np.transpose(): This function transpose a matrix by moving the rows data to the column and columns data to the rows.

g) np.round(): function that rounds an array to the given number of decimals.

h) np.expand_dims(): This function is used to expand the shape of an input array that is passed to it.

i) np.squeeze(): It eliminates axes that have a length of one, reducing the array's dimensionality. If a dimension has a size greater than one, the shape remains unchanged.

j) np.digitize(): This function takes an array of values and splits them into bins or categories of equal size. The function will then assign each element in the array a number corresponding to the bin it is in.

In [14]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [16]:
sample = np.array([[1, 3, 5], [11, 35, 56]])  
sample_ravelled = np.ravel(sample)  
sample_ravelled

array([ 1,  3,  5, 11, 35, 56])

In [17]:
sample = np.arange(16.0).reshape(4,4)	   
np.hsplit(sample, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]